/// libBIL top-level interface
/// @file libbfd.idl
/// @author Sang Kil Cha <sangkil.cha\@gmail.com>

/*
Copyright (c) 2014, Sang Kil Cha
All rights reserved.
This software is free software; you can redistribute it and/or
modify it under the terms of the GNU Library General Public
License version 2, with the special exception on linking
described in file LICENSE.

This software is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*/

import "libbfd/bfdarch.idl";

/// handle
typedef [abstract,ptr] void* bhp;

/// section data (data, startaddr, endaddr)
quote(H, "#include <caml/mlvalues.h>");
typedef [mltype("(string * int64 * int64) list"),
         c2ml(c2ml_identity), ml2c(ml2c_identity)]
struct _sec_data* sec_data;

bhp new_bfd_from_buf( [in] enum architecture arch,
                      [in] int machine );
bhp new_bfd_from_file( [in,string] const char* filename );

void delete_bfd( bhp abfd );

void update_disasm_info( [in] bhp _p,
                         [in,string] char* buffer,
                         [in] int len,
                         [in] unsigned __int64 addr );

[string] char* disasm( [in] bhp _p,
                       [in] unsigned __int64 addr );

unsigned __int64 get_entry_point( [in] bhp _p );

int get_instr_length( [in] bhp _p, [in] __int64 addr );

sec_data get_section_data( [in] bhp _p );

